import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { FaInstagram, FaYoutube } from "react-icons/fa";
import { FaBluetooth, FaEnvelope, FaPhoneSquareAlt } from "react-icons/fa";
import Hero from "../components/Hero";
import styles from "../styles/Contact.module.css";
import { styled } from "../stitches.config";

import image from "../public/images/ozgePhoto1.jpeg";

const Contact = () => {
  return (
    <>
      <Head>
        <title>Uzman Psikolog Özge Demirsu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <main className={styles.main}>
        <div className={styles.about}>
          <div className="leftSideBar">
            <div className={styles.avatarWrapper}>
              <div className={styles.avatar}>
                <Image src={image} alt="Hero" layout="fill" objectFit="cover" />
              </div>
            </div>
            <div className={styles.blank}></div>
            <div className={styles.bio}>
              <ul>
                <li>Uzm. Psk. özge Demirsu</li>
                <li>İzdüşüm Psikoloji</li>
              </ul>
            </div>
            <div className={styles.address}>
              <ul>
                <li className="street1">Şehit Ergün Köncü Caddesi</li>
                <li className="street2">No:25 Kat:2 İş yeri No: 4</li>
                <li className="street3"></li>
                <li className="postCode"></li>
                <li className="district">Yahya Kaptan Mahallesi</li>
                <li className="city">İzmit/Kocaeli</li>
                <li className="country">Türkiye</li>
              </ul>
            </div>
            <div className={styles.phone}>
              <ul>
                <li className="phone1">+90 (530) 874 16 31</li>
                <li className="phone2"></li>
              </ul>
            </div>
            <div className={styles.email}>
              <ul>
                <li className="email1">
                  <ul className={styles.iconWithText}>
                    <li>
                      <FaEnvelope />
                    </li>
                    <li>ozge@izdusumpsikoloji.com</li>
                  </ul>
                </li>
                <li className="email2"></li>
              </ul>
            </div>
            <div className={styles.socialMedia}>
              <ul>
                <li>
                  <a
                    href="https://instagram.com/tango.teknik?igshid=ksg4wxslqht7"
                    target="_blank"
                    rel="noreferrer"
                    aria-label="Instagram"
                  >
                    <ul className={styles.iconWithText}>
                      <li>
                        <FaInstagram />
                      </li>
                      <li>Instagram</li>
                    </ul>
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.youtube.com/user/stylishtango"
                    target="_blank"
                    rel="noreferrer"
                    aria-label="Youtube"
                  >
                    <ul className={styles.iconWithText}>
                      <li>
                        <FaYoutube />
                      </li>
                      <li>YouTube</li>
                    </ul>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div className={styles.content}>
            <div className="callout">
              <p>
                Amacım, birlikte hedefe ulaşmak için çalışacağımız konforlu ve
                güvenli bir ortam yaratmak.
              </p>
              <p>
                Ruhsal hastalıkların ve davranışsal sorunların değerlendirilmesi
                ve tedavisi ile ilgili psikoloji dalında sertifikalı bir
                uzmanım.
              </p>
            </div>
            <div className={styles.mapWrapper}>
              <iframe
                className={styles.map}
                src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1505.6862367096228!2d29.041463000000004!3d40.99522!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x58aabbe3a3b12115!2zR8O8cmF5IMSwxZ8gSGFuxLE!5e0!3m2!1sen!2str!4v1636901720722!5m2!1sen!2str"
                // width="100%"
                // height="100%"
                // style="border:0;"
                // allowfullscreen=""
                loading="lazy"
              ></iframe>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Contact;
